services:
  watchdog:
    build: .
    container_name: watchdog
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    volumes:
      - watchdog_repo:/opt/watchdog
      - ${HOME}/configs/watchdog/config.json:/config/config.json:ro

volumes:
  watchdog_repo:
